title: dvdtsb's epic blog
remote_theme: jekyll/minima
markdown: GFM
minima:
  skin: classic 
header_pages:
  - index.md
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/DVDTSB" }
permalink: /:categories/:title/
