baseURL = "https://dvdtsb.github.io/personal/"
languageCode = 'en-us'
title = "dvdtsb's epic blog"
theme = 'risotto'

[params.about]
title= "dvdtsb's epic blog"
description= "the most epic blog ever or something"

[params.theme]
palette = "base16-dark"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/DVDTSB"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
url = "https://discord.gg/Ef39zuKe8K"

[[params.socialLinks]]
icon = "fa-brands fa-twitter"
title = "Twitter"
url = "https://twitter.com/dvdtsb"


[module]
[[module.imports]]
  path = 'github.com/hugomods/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
